### ISSUE TITLE
Mustache.php error

### ISSUE THREAD

**Issue by OmerGafny** [TheDMSGroup/mautic-contact-client#244]
Hi guys, tried your contact source plugin and really liked it, so i thought i give this one a shot as well. I was able to install it, but for some reason im always getting the error below that prevents it from working:
Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "Mustache_Engine" from the global namespace. Did you forget a "use" statement?"

**Comment by heathdutton** [comment]
You need composer install, or to composer require the mustache engine.

**Comment by OmerGafny** [comment]
Hi Heath should i run the command in a specific path of th plugin?

**Comment by heathdutton** [comment]
https://github.com/TheDMSGroup/mautic-contact-client#installation--usage 

The proper way to install this plugin is via composer at the root of your mautic installation (where the composer.json file is).

**Comment by OmerGafny** [comment]
Thanks, ill try it
