### ISSUE TITLE
Not working on Mautic version 2.15.3 

### ISSUE THREAD

**Issue by zackrspv** [TheDMSGroup/mautic-contact-client#245]
Were you able to get this to work on 2.15.3? 

We follow the instructions to run the `composer require` command, then visit the `/reload` page for the plugins, but still says 0 plugins found to update. 

I have cleared cache, same result.

**Comment by heathdutton** [comment]
Interresting... did the folder /plugins/MauticContactClientBundle get added under the mautic installation? If not, then you might have ran that command in the wrong location, or as the wrong user...
